# [About the data set](https://www.kaggle.com/datasets/rzemouri/oncotypedx-breast-cancer-dataset?resource=download)
Ο Oncotype DX (ODX) είναι μια υπογραφή έκφρασης πολλαπλών γονιδίων που έχει σχεδιαστεί για ασθενείς με καρκίνο του μαστού με θετικό υποδοχέα οιστρογόνων (ER) και αρνητικό υποδοχέα του ανθρώπινου επιδερμικού αυξητικού παράγοντα 2 (HER2) για την πρόβλεψη του σκορ υποτροπής (RS) και του οφέλους της χημειοθεραπείας (CT). Σκοπός της μελέτης μας είναι η ανάπτυξη ενός εργαλείου πρόβλεψης για τις τρεις κατηγορίες RS που βασίζεται σε βαθιά πολυεπίπεδα perceptrons (DMLP) και χρησιμοποιεί μόνο τις μορφοανοσοανοσολογικές μεταβλητές. Πραγματοποιήσαμε μια αναδρομική κοόρτη 320 ασθενών που υποβλήθηκαν σε έλεγχο ODX από τρία γαλλικά νοσοκομεία. Καταγράφηκαν τα κλινικοπαθολογικά χαρακτηριστικά. Κατασκευάσαμε ένα μοντέλο ταξινόμησης με επιβλεπόμενη μηχανική μάθηση χρησιμοποιώντας το λογισμικό Matlab με 152 περιπτώσεις για την εκπαίδευση και 168 περιπτώσεις για τη δοκιμή. Χρησιμοποιήθηκαν τρεις ταξινομητές για την εκμάθηση των τριών κατηγοριών κινδύνου της ODX, δηλαδή του χαμηλού, του ενδιάμεσου και του υψηλού κινδύνου. Τα πειραματικά αποτελέσματα παρέχουν την περιοχή κάτω από την καμπύλη (AUC), αντίστοιχα, για τις τρεις κατηγορίες κινδύνου: 0,63 [95% διάστημα εμπιστοσύνης: (0,5446, 0,7154), p < 0,001], 0,59 [95% διάστημα εμπιστοσύνης: (0,5031, 0,6769), p < 0,001], 0,75 [95% διάστημα εμπιστοσύνης: (0,6184, 0,8816), p < 0,001]. Το ποσοστό συμφωνίας μεταξύ του πραγματικού RS και του προβλεπόμενου RS κυμάνθηκε από 53 έως 56% για κάθε κατηγορία μεταξύ DMLP και ODX. Το ποσοστό συμφωνίας της συνδυασμένης ομάδας χαμηλού και ενδιάμεσου κινδύνου ήταν 85%. αναπτύξαμε ένα προγνωστικό μοντέλο μηχανικής μάθησης που θα μπορούσε να βοηθήσει στον καθορισμό της RS του ασθενούς. Επιπλέον, ενσωματώσαμε τα ιστοπαθολογικά δεδομένα και τα αποτελέσματα της DMLP για την επιλογή όγκου για τη δοκιμή ODX. Έτσι, η διαδικασία αυτή επιτρέπει την πιο συναφή χρήση των ιστοπαθολογικών δεδομένων και βελτιστοποιεί και ενισχύει αυτές τις πληροφορίες.

Σχετικές εργασίες και αίτηση αναφοράς:

Πρόβλεψη της βαθμολογίας υποτροπής του Oncotype DX με τη χρήση βαθιών πολυεπίπεδων perceptrons σε καρκίνο του μαστού με θετικούς υποδοχείς οιστρογόνων και αρνητικό HER2
Μάιος 2020 Καρκίνος του μαστού 27(5)
DOI: 10.1007/s12282-020-01100-4

Διάγνωση του καρκίνου του μαστού με βάση την από κοινού επιλογή μεταβλητών και το Constructive Deep Neural Network, Μάρτιος 2018, Συνέδριο: 2018 IEEE 4th Middle East Conference on Biomedical Engineering (MECBME), DOI:10.1109/MECBME.2018.8402426

Constructive Deep Neural Network for Breast Cancer Diagnosis, Ιανουάριος 2018, IFAC-PapersOnLine 51(27):98-103, DOI:10.1016/j.ifacol.2018.11.660

## Target feature
    Statur ODX
    -   1 = low value (RS<18)
    -   2 = mid value (RS18-30)
    -   3 = high value (RS>30)

In [7]:
#Libraries
import pandas as pd

In [8]:
#pandas settings
pd.set_option('display.max_columns',58)
missing_values = ['NA', 'NaN', 'N/A', 'NR', ' ']

In [9]:
# loading the dataset
#pc version 
# file_path = r'C:\Users\thomo\Desktop\Personal\Uni\Ptixiaki\DataSet\DataSet.xlsx'
#laptop version
file_path = 'DataSet/DataSet.xlsx'
df = pd.read_excel(file_path)
df.replace(missing_values, inplace=True)
target = 'Statut ODX'

In [10]:
df.head()

,N°Bloc,Type de prélèvement,Bloc ODX,Sexe,DDN,Date diag,Age au diag,Ménopause,ATCD K sein,Consultation oncogénétique,Mutation,Taille tm (mm),Type de gg,Statut ganglionnaire,Nombre de gg+/nb de gg prélevés,Type histo,Type histo associé,Grade SBR,Grade glandes,Grade nucléaire,Grade mitoses,Emboles vasculaires,Envahissement périnerveux,% Stroma,% CT,Topographie infiltrat,Stade pTNM,RE (%),RE intensité,RE Allred,RP (%),RP intensité,RP Allred,HER2 IHC,HER2 SISH,Ki67,% Lt stroma,% CD8 dans tumeur,P53,P53 (%),P53 intensité,Score Oncotype,Distant recurrence (%),Statut ODX,RE Oncotype,RE status O,RP Oncotype,RP status O,HER2 Oncotype,HER 2 status O,Chirurgie,HT,RT,Chimithérapie,DDN.1,EDN,Récidive,Unnamed: 57
0,12.11.07.046,1,E,1,1934-12-26,2012-11-16,77.945205,1,2,NaN,NaN,14,1,0.0,0/1,3,1,3,3,2,3,0,0,20,80.0,2.0,T1cN0(sn)(i-),100,3,8,100,3,8,NaN,NaN,11,5,0.0,0*,30.0,1,2,0.04,1,11.9,positive,8.8,positive,7.8,négative,1,1,1,0,2016-06-15 00:00:00,V,0,NaN
1,12.12.18.104,1,T21,1,1944-04-08,2013-01-03,68.786301,1,0,NaN,NaN,15,1,0.0,0/1,1,5,3,3,3,2,0,0,30,70.0,1.0,T1cN0(sn)(i-),90,3,8,90,3,8,NaN,NaN,24,5,0.0,0*,20.0,1,15,0.1,1,11.1,positive,9.3,positive,9.9,négative,2,1,1,0,2016-10-28 00:00:00,V,0,NaN
2,13.01.08.103,1,R1,1,1950-08-16,2013-01-17,62.465753,1,0,NaN,NaN,6,1,1.0,0.5,1,1,2,3,2,1,0,0,70,30.0,3.0,T1bN1a(sn),95,3,8,60,3,7,NaN,NaN,20,30,5.0,0*,10.0,1,27,0.18,2,8.4,positive,6.1,positive,8,négative,2,1,1,0,2015-10-16 00:00:00,V,0,NaN
3,13.01.09.009,1,I3,1,1966-05-16,2013-01-18,46.709589,0,0,NaN,NaN,80,1,3.0,0/1,2,2 + 3,2,3,2,1,0,0,30,70.0,1.0,T3N0(sn)(i+),90,2,7,100,3,8,NaN,NaN,11,5,1.0,0*,30.0,1,12,0.08,1,7.8,positive,8.5,positive,9.4,négative,4,1,1,0,2018-01-18 00:00:00,V,0,NaN
4,13.02.05.076,1,A5,1,1954-12-15,2013-02-14,58.208219,0,0,1.0,6.0,30,1,0.0,0/1,1,1,2,3,2,1,0,0,20,80.0,2.0,T2N0(sn)(i-),100,3,8,2,2,4,NaN,NaN,10,5,0.0,0*,10.0,1,16,0.1,1,10.3,positive,4,négative,9.2,négative,2,1,1,0,2016-10-09 00:00:00,V,0,NaN

In [11]:
def columnType():
    # Iterate over each column
    for column in df.columns:
        print("----", column, "----")
    
    # Calculate missing values
        missing_count = df[column].isnull().sum()
        print("Missing values:", missing_count)
    
    
    # Check if column is mostly numeric 
        if pd.to_numeric(df[column], errors='coerce').notnull().sum() / len(df[column]) > 0.9: #cheks if for the most part the is numeric
            df[column] = pd.to_numeric(df[column])

        # Calculate statistics
            std_deviation = df[column].std()
            print("Standard deviation:", std_deviation)
        
            mean_value = df[column].mean()
            print("Mean value:", mean_value)
        
            max_value = df[column].max()
            print("Maximum value:", max_value)
        
            min_value = df[column].min()
            print("Minimum value:", min_value)
        
        else:
            print("The feature named", column, "is not numeric")
        
        print("\n")
columnType()

---- N°Bloc ----
Missing values: 0
The feature named N°Bloc is not numeric


---- Type de prélèvement ----
Missing values: 0
Standard deviation: 0.3198398158268636
Mean value: 0.8847352024922118
Maximum value: 1
Minimum value: 0


---- Bloc ODX ----
Missing values: 33
The feature named Bloc ODX is not numeric


---- Sexe ----
Missing values: 0
Standard deviation: 0.05581455721859476
Mean value: 0.9968847352024922
Maximum value: 1
Minimum value: 0


---- DDN ----
Missing values: 0
Standard deviation: 3.621924357059397e+17
Mean value: -3.579145570093458e+17
Maximum value: 503625600000000000
Minimum value: -1236729600000000000


---- Date diag ----
Missing values: 0
Standard deviation: 4.867620098067768e+16
Mean value: 1.4319069308411215e+18
Maximum value: 1547164800000000000
Minimum value: 1345593600000000000


---- Age au diag ----
Missing values: 0
Standard deviation: 11.288386101291726
Mean value: 56.75486706781036
Maximum value: 83.84383561643835
Minimum value: 30.367123287671234


---- Ménopause ----
Missing values: 1
Standard deviation: 0.5496864309893351
Mean value: 0.70625
Maximum value: 2.0
Minimum value: 0.0


---- ATCD K sein ----
Missing values: 0
Standard deviation: 0.47238788249327457
Mean value: 0.14330218068535824
Maximum value: 2
Minimum value: 0


---- Consultation oncogénétique ----
Missing values: 270
The feature named Consultation oncogénétique is not numeric


---- Mutation  ----
Missing values: 271
The feature named Mutation  is not numeric


---- Taille tm (mm) ----
Missing values: 0
Standard deviation: 11.629812171855916
Mean value: 19.90031152647975
Maximum value: 100
Minimum value: 2


---- Type de gg ----
Missing values: 0

ValueError: Unable to parse string "1 + 2" at position 22

## Βρόμικο dataset
Υπάρχουν πολλές περιπτώσεις με << λάθος >> συμβολισμούς, για την αντιμετώπιση τους θα προσπαθήσω αρχικά να απομονώσω τις << σημειώσεις >> όπου υπάρχουν μέσα στο data set και προκαλούν error. Στην συνέχεια θα προσπαθήσω να ερμηνεύσω την κάθε μία αντικαθιστώντας την σύμφωνα με τις οδηγίες του dataset. Αν δεν είναι δυνατή μία τέτοια ενέργεια θα αποβάλω αυτό το δήγμα σε ένα unclean dataset που θα χρησιμοποιηθεί είτε για test είτε ως αποθήκη δηγμάτων μέχρι να βρεθεί η ερμηνεία τους.


### Type de gg (Cleaning)
Μετάφραση από gpt
> τύπος gg: τύπος αδένα
> - 0 = χωρίς αισθητήρα αδένων ή αφαίρεση
> - 1 = αισθητήρας αδένων
> - 2 = άξονας αφαίρεσης

το 1+2 συμβολίζει ότι ανήκει στην κατηγορία 1 και 2 για να μην γίνεται πρόβλημα στην αντιμετώπιση του, θα το μετατρέψω σε μια νέα κατηγορία 3. Κάθε κατηγορία θα παραμείνει ως μια ακέραια τιμή για αρχή για να είναι πιο κοντά στην αρχική απεικόνιση του σετ και στην πορεία αν κριθεί απαραίτητο θα μετατραπούν σε τυχαία σύμβολα.

In [12]:
df['Type de gg'] = pd.to_numeric(df['Type de gg'], errors='coerce').fillna(3)

print(df['Type de gg'])

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
316    1.0
317    1.0
318    1.0
319    1.0
320    1.0
Name: Type de gg, Length: 321, dtype: float64

## Επόμενο βρώμικο feature

In [13]:
columnType()

---- N°Bloc ----
Missing values: 0
The feature named N°Bloc is not numeric


---- Type de prélèvement ----
Missing values: 0
Standard deviation: 0.3198398158268636
Mean value: 0.8847352024922118
Maximum value: 1
Minimum value: 0


---- Bloc ODX ----
Missing values: 33
The feature named Bloc ODX is not numeric


---- Sexe ----
Missing values: 0
Standard deviation: 0.05581455721859476
Mean value: 0.9968847352024922
Maximum value: 1
Minimum value: 0


---- DDN ----
Missing values: 0
Standard deviation: 3.621924357059397e+17
Mean value: -3.579145570093458e+17
Maximum value: 503625600000000000
Minimum value: -1236729600000000000


---- Date diag ----
Missing values: 0
Standard deviation: 4.867620098067768e+16
Mean value: 1.4319069308411215e+18
Maximum value: 1547164800000000000
Minimum value: 1345593600000000000


---- Age au diag ----
Missing values: 0
Standard deviation: 11.288386101291726
Mean value: 56.75486706781036
Maximum value: 83.84383561643835
Minimum value: 30.367123287671234


---- Ménopause ----
Missing values: 1
Standard deviation: 0.5496864309893351
Mean value: 0.70625
Maximum value: 2.0
Minimum value: 0.0


---- ATCD K sein ----
Missing values: 0
Standard deviation: 0.47238788249327457
Mean value: 0.14330218068535824
Maximum value: 2
Minimum value: 0


---- Consultation oncogénétique ----
Missing values: 270
The feature named Consultation oncogénétique is not numeric


---- Mutation  ----
Missing values: 271
The feature named Mutation  is not numeric


---- Taille tm (mm) ----
Missing values: 0
Standard deviation: 11.629812171855916
Mean value: 19.90031152647975
Maximum value: 100
Minimum value: 2


---- Type de gg ----
Missing values: 0
Standard deviation: 0.5920192227661283
Mean value: 1.1838006230529594
Maximum value: 3.0
Minimum value: 0.0


---- Statut ganglionnaire ----
Missing values: 9
Standard deviation: 0.8873382192509189
Mean value: 0.7051282051282052
Maximum value: 3.0
Minimum value: 0.0


---- Nombre de gg+/nb de gg prélevés ----
Missing values: 9
The feature named Nombre de gg+/nb de gg prélevés is not numeric


---- Type histo ----
Missing values: 0

ValueError: Unable to parse string "1 + 3" at position 148

### Type histo
Μετάφραση από gpt
> Ιστολογικός τύπος:
> - 1 = διεισδυτικός καρκίνος μη-ειδικού τύπου (= διεισδυτικός καρκίνος ακαναλικού τύπου)
> - 2 = διεισδυτικός λοβουλώδης καρκίνος
> - 3 = διεισδυτικός μυξώδης καρκίνος
> - 4 = διεισδυτικός καρκίνος μη-ειδικού τύπου με ενδοκρινή διαφοροποίηση
> - 5 = διεισδυτικός καρκίνος με δαχτυλίδια και τρύπημα
> - 6 = διεισδυτικός μικροπαπιλλώδης καρκίνος
> - 7 = διεισδυτικός παπιλλώδης καρκίνος

In [14]:
def problematicValues(col):
    non_numeric_values = df.loc[~df[col].apply(pd.to_numeric, errors='coerce').notnull(), col]
    print(non_numeric_values)

problematicValues("Type histo")

148    1 + 3
165    1 + 3
195    1 + 6
264    1 + 2
269    1 + 2
299    1 + 2
Name: Type histo, dtype: object

Πρέπει λοιπόν τις τιμές αυτές να της μετατρέψω σε νέες κατηγορίες, αλφαριθμητικές καθώς δεν μπορούν να έχουν κάποια αριθμητική συνοχή πχ αν κάποιος ανοική στην κατηγορία 1 και 3 θα ανοικεί στην κατηγορία 4 καθώς η κατηγορία αυτή αντιπροσοπεύει μια διαφορετική ομάδα. Έχοντας το σε μορφή κειμένου θα μπορώ να έχω περισσότερη συνοχή καθώς η κατηγορίες θα μετονομαστούν σε A B C D E F G και αν κάποιο ανοίχει στην 1 + 3 θα ονομαστή AC κλπ

In [15]:
mapping = {0:'Zero', 1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E', 6: 'F', 7: 'G'}
def convert_value(value):
    if isinstance(value, int):
        return mapping.get(value, '')
    elif isinstance(value, str):
        parts = value.split('+')
        if all(part.strip().isdigit() for part in parts):
            return ''.join([mapping.get(int(part.strip()), '') for part in parts])
    return ''
df['Type histo'] = df['Type histo'].apply(convert_value)

In [16]:
print(df['Type histo'].to_string(index=True))

0       C
1       A
2       A
3       B
4       A
5       A
6       A
7       A
8       A
9       A
10      A
11      A
12      A
13      A
14      A
15      A
16      A
17      A
18      A
19      A
20      A
21      A
22      A
23      A
24      A
25      A
26      B
27      A
28      A
29      A
30      A
31      A
32      A
33      A
34      A
35      A
36      A
37      A
38      A
39      B
40      B
41      A
42      A
43      A
44      A
45      A
46      A
47      A
48      A
49      A
50      A
51      A
52      A
53      A
54      A
55      C
56      A
57      A
58      A
59      A
60      A
61      B
62      A
63      A
64      A
65      A
66      A
67      A
68      A
69      A
70      A
71      A
72      A
73      A
74      A
75      A
76      A
77      A
78      A
79      A
80      A
81      A
82      A
83      A
84      A
85      A
86      A
87      A
88      A
89      A
90      A
91      A
92      A
93      A
94      A
95      A
96      C
97      A
98      F
99      A
100     A
101     A
102     B
103     A
104     A
105     B
106     A
107     A
108     A
109     A
110     A
111     B
112     A
113     A
114     A
115     A
116     A
117     A
118     A
119     A
120     A
121     A
122     A
123     A
124     A
125     A
126     A
127     A
128     A
129     A
130     A
131     A
132     A
133     A
134     A
135     C
136     A
137     A
138     A
139     A
140     A
141     A
142     A
143     B
144     A
145     A
146     A
147     A
148    AC
149     A
150     A
151     A
152     A
153     A
154     A
155     A
156     D
157     B
158     E
159     A
160     A
161     A
162     A
163     B
164     A
165    AC
166     A
167     A
168     A
169     A
170     A
171     A
172     A
173     A
174     A
175     A
176     A
177     A
178     A
179     A
180     A
181     A
182     A
183     A
184     C
185     A
186     A
187     A
188     A
189     A
190     A
191     A
192     A
193     A
194     A
195    AF
196     A
197     A
198     A
199     A
200     A
201     A
202     A
203     A
204     A
205     A
206     A
207     A
208     A
209     A
210     A
211     A
212     A
213     A
214     A
215     A
216     A
217     A
218     A
219     A
220     A
221     A
222     A
223     A
224     A
225     A
226     A
227     A
228     A
229     B
230     A
231     A
232     A
233     A
234     A
235     A
236     A
237     A
238     A
239     A
240     A
241     A
242     A
243     B
244     A
245     A
246     A
247     A
248     A
249     A
250     A
251     A
252     A
253     A
254     A
255     A
256     A
257     A
258     A
259     A
260     A
261     A
262     A
263     A
264    AB
265     A
266     A
267     A
268     B
269    AB
270     A
271     A
272     A
273     A
274     A
275     A
276     A
277     A
278     A
279     A
280     A
281     A
282     A
283     A
284     G
285     A
286     A
287     A
288     A
289     A
290     A
291     A
292     A
293     A
294     B
295     A
296     A
297     A
298     A
299    AB
300     A
301     A
302     G
303     A
304     A
305     A
306     A
307     A
308     A
309     A
310     A
311     A
312     A
313     A
314     B
315     A
316     A
317     A
318     A
319     A
320     A

In [17]:
columnType()

---- N°Bloc ----
Missing values: 0
The feature named N°Bloc is not numeric


---- Type de prélèvement ----
Missing values: 0
Standard deviation: 0.3198398158268636
Mean value: 0.8847352024922118
Maximum value: 1
Minimum value: 0


---- Bloc ODX ----
Missing values: 33
The feature named Bloc ODX is not numeric


---- Sexe ----
Missing values: 0
Standard deviation: 0.05581455721859476
Mean value: 0.9968847352024922
Maximum value: 1
Minimum value: 0


---- DDN ----
Missing values: 0
Standard deviation: 3.621924357059397e+17
Mean value: -3.579145570093458e+17
Maximum value: 503625600000000000
Minimum value: -1236729600000000000


---- Date diag ----
Missing values: 0
Standard deviation: 4.867620098067768e+16
Mean value: 1.4319069308411215e+18
Maximum value: 1547164800000000000
Minimum value: 1345593600000000000


---- Age au diag ----
Missing values: 0
Standard deviation: 11.288386101291726
Mean value: 56.75486706781036
Maximum value: 83.84383561643835
Minimum value: 30.367123287671234


---- Ménopause ----
Missing values: 1
Standard deviation: 0.5496864309893351
Mean value: 0.70625
Maximum value: 2.0
Minimum value: 0.0


---- ATCD K sein ----
Missing values: 0
Standard deviation: 0.47238788249327457
Mean value: 0.14330218068535824
Maximum value: 2
Minimum value: 0


---- Consultation oncogénétique ----
Missing values: 270
The feature named Consultation oncogénétique is not numeric


---- Mutation  ----
Missing values: 271
The feature named Mutation  is not numeric


---- Taille tm (mm) ----
Missing values: 0
Standard deviation: 11.629812171855916
Mean value: 19.90031152647975
Maximum value: 100
Minimum value: 2


---- Type de gg ----
Missing values: 0
Standard deviation: 0.5920192227661283
Mean value: 1.1838006230529594
Maximum value: 3.0
Minimum value: 0.0


---- Statut ganglionnaire ----
Missing values: 9
Standard deviation: 0.8873382192509189
Mean value: 0.7051282051282052
Maximum value: 3.0
Minimum value: 0.0


---- Nombre de gg+/nb de gg prélevés ----
Missing values: 9
The feature named Nombre de gg+/nb de gg prélevés is not numeric


---- Type histo ----
Missing values: 0
The feature named Type histo is not numeric


---- Type histo associé ----
Missing values: 0

ValueError: Unable to parse string "2 + 3" at position 3

### Type histo associé

In [18]:
problematicValues("Type histo associé")

3          2 + 3
8          1 + 2
26         2 + 3
47         1 + 2
102        2 + 4
103        1 + 2
104    1 + 2 + 3
133        1 + 5
191        1 + 2
220        1 + 4
240        1 + 2
269        1 + 2
279        3 + 4
284        1 + 2
294        1 + 2
304          1+4
314          2+3
Name: Type histo associé, dtype: object

In [ ]:
df['Type histo associé'] = df['Type histo associé'].apply(convert_value)
df['Type histo associé'] = df['Type histo associé'].apply(convert_multi_plus)

print(df['Type histo associé'].to_string(index=True))

In [20]:
print(df['Type histo associé'].to_string(index=True))

0         A
1         E
2         A
3        BC
4         A
5         A
6         A
7         B
8        AB
9         A
10        A
11        A
12        A
13        A
14        A
15     Zero
16     Zero
17     Zero
18        A
19        A
20        A
21        A
22        A
23        A
24        A
25        A
26       BC
27        A
28     Zero
29        A
30        A
31        A
32        A
33     Zero
34        E
35     Zero
36        A
37     Zero
38     Zero
39        B
40     Zero
41        A
42        A
43     Zero
44     Zero
45        A
46        A
47       AB
48     Zero
49        A
50     Zero
51     Zero
52        A
53     Zero
54     Zero
55        G
56     Zero
57        A
58        A
59     Zero
60     Zero
61     Zero
62     Zero
63     Zero
64     Zero
65        A
66        A
67     Zero
68     Zero
69        A
70     Zero
71     Zero
72     Zero
73     Zero
74     Zero
75        A
76        A
77        A
78     Zero
79        A
80        A
81     Zero
82     Zero
83     Zero
84        A
85     Zero
86     Zero
87        A
88     Zero
89        A
90        A
91     Zero
92     Zero
93     Zero
94     Zero
95        A
96        A
97        A
98     Zero
99        A
100       A
101       A
102      BD
103      AB
104     ABC
105       A
106       A
107       A
108       A
109       A
110       A
111       C
112       A
113       A
114    Zero
115       A
116       A
117       A
118       A
119       A
120       A
121       A
122    Zero
123       A
124       A
125       A
126    Zero
127       A
128    Zero
129       A
130       A
131       A
132       A
133      AE
134       A
135       F
136    Zero
137    Zero
138       A
139       A
140       A
141       A
142       A
143       B
144       A
145       A
146       A
147       A
148       A
149       A
150       A
151       A
152    Zero
153       A
154       A
155    Zero
156    Zero
157       B
158       A
159       A
160       A
161       A
162       A
163    Zero
164       A
165       A
166       A
167       A
168       A
169    Zero
170       A
171    Zero
172       A
173       A
174       A
175       A
176    Zero
177       A
178       A
179       A
180    Zero
181       A
182       A
183       A
184       A
185       A
186       A
187    Zero
188       A
189       A
190       A
191      AB
192       A
193       A
194       A
195       A
196       A
197       A
198       A
199       A
200       A
201       A
202       A
203       A
204       A
205       A
206    Zero
207       A
208    Zero
209       A
210       A
211       A
212       A
213       D
214    Zero
215    Zero
216       A
217       A
218       A
219    Zero
220      AD
221    Zero
222    Zero
223       A
224       A
225       B
226    Zero
227    Zero
228       D
229    Zero
230       A
231    Zero
232       A
233       A
234    Zero
235       A
236       A
237    Zero
238       A
239       A
240      AB
241    Zero
242       A
243       B
244       A
245       A
246       A
247    Zero
248       A
249       A
250    Zero
251       A
252    Zero
253       A
254    Zero
255    Zero
256       A
257       A
258    Zero
259       A
260    Zero
261       A
262    Zero
263       A
264       B
265       B
266       B
267       A
268    Zero
269      AB
270       A
271       A
272    Zero
273    Zero
274    Zero
275    Zero
276    Zero
277    Zero
278       A
279      CD
280       A
281       A
282    Zero
283    Zero
284      AB
285    Zero
286       A
287       A
288       A
289       A
290       A
291       A
292       A
293       A
294      AB
295       A
296       A
297       A
298    Zero
299       A
300       A
301    Zero
302    Zero
303       A
304      AD
305       A
306    Zero
307       A
308       A
309    Zero
310       A
311       A
312       A
313       A
314      BC
315       A
316    Zero
317       A
318       A
319       A
320       A

In [21]:
columnType()

---- N°Bloc ----
Missing values: 0
The feature named N°Bloc is not numeric


---- Type de prélèvement ----
Missing values: 0
Standard deviation: 0.3198398158268636
Mean value: 0.8847352024922118
Maximum value: 1
Minimum value: 0


---- Bloc ODX ----
Missing values: 33
The feature named Bloc ODX is not numeric


---- Sexe ----
Missing values: 0
Standard deviation: 0.05581455721859476
Mean value: 0.9968847352024922
Maximum value: 1
Minimum value: 0


---- DDN ----
Missing values: 0
Standard deviation: 3.621924357059397e+17
Mean value: -3.579145570093458e+17
Maximum value: 503625600000000000
Minimum value: -1236729600000000000


---- Date diag ----
Missing values: 0
Standard deviation: 4.867620098067768e+16
Mean value: 1.4319069308411215e+18
Maximum value: 1547164800000000000
Minimum value: 1345593600000000000


---- Age au diag ----
Missing values: 0
Standard deviation: 11.288386101291726
Mean value: 56.75486706781036
Maximum value: 83.84383561643835
Minimum value: 30.367123287671234


---- Ménopause ----
Missing values: 1
Standard deviation: 0.5496864309893351
Mean value: 0.70625
Maximum value: 2.0
Minimum value: 0.0


---- ATCD K sein ----
Missing values: 0
Standard deviation: 0.47238788249327457
Mean value: 0.14330218068535824
Maximum value: 2
Minimum value: 0


---- Consultation oncogénétique ----
Missing values: 270
The feature named Consultation oncogénétique is not numeric


---- Mutation  ----
Missing values: 271
The feature named Mutation  is not numeric


---- Taille tm (mm) ----
Missing values: 0
Standard deviation: 11.629812171855916
Mean value: 19.90031152647975
Maximum value: 100
Minimum value: 2


---- Type de gg ----
Missing values: 0
Standard deviation: 0.5920192227661283
Mean value: 1.1838006230529594
Maximum value: 3.0
Minimum value: 0.0


---- Statut ganglionnaire ----
Missing values: 9
Standard deviation: 0.8873382192509189
Mean value: 0.7051282051282052
Maximum value: 3.0
Minimum value: 0.0


---- Nombre de gg+/nb de gg prélevés ----
Missing values: 9
The feature named Nombre de gg+/nb de gg prélevés is not numeric


---- Type histo ----
Missing values: 0
The feature named Type histo is not numeric


---- Type histo associé ----
Missing values: 0
The feature named Type histo associé is not numeric


---- Grade SBR ----
Missing values: 0
Standard deviation: 0.6150532484609504
Mean value: 2.2554517133956384
Maximum value: 3
Minimum value: 1


---- Grade glandes ----
Missing values: 0
Standard deviation: 0.44158363411589785
Mean value: 2.7725856697819315
Maximum value: 3
Minimum value: 1


---- Grade nucléaire  ----
Missing values: 0
Standard deviation: 0.5088201795112706
Mean value: 2.311526479750779
Maximum value: 3
Minimum value: 1


---- Grade mitoses ----
Missing values: 0
Standard deviation: 0.7098412573187757
Mean value: 1.8660436137071652
Maximum value: 3
Minimum value: 1


---- Emboles vasculaires ----
Missing values: 0
Standard deviation: 0.4001557329239459
Mean value: 0.19937694704049844
Maximum value: 1
Minimum value: 0


---- Envahissement périnerveux ----
Missing values: 0
Standard deviation: 0.3160429995587522
Mean value: 0.11214953271028037
Maximum value: 1
Minimum value: 0


---- % Stroma ----
Missing values: 17

ValueError: Unable to parse string "BLOC NON TROUVE" at position 13

### Stroma 
Από ότι φαίνεται από το dataset έχουμε 3 δεδομένα τα οποία συνδέονται μεταξύ τους στα οποία υπ´αρχουν διαφορετικές μορφές missing Values υπάρχουν αυτά στα οποία δεν *βρέθεικε* τιμή τα οποία έχουν συγκεκριμένες κατηγορίες στα γαλλικά και αυτά που απλός είναι missing values, τα οποία δεν δημιουργούν πρόβλημα σε αυτή την φάση που βρίσκομαι.
Τις << περίεργες >> τιμές πρέπει να δω αν αξίζει να υπάρχουν στο dataset και αν ναι πώς τις μεταφράζω σε αριθμητικές.